In [135]:
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings('ignore')
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression,Lasso,Ridge
from sklearn.tree import DecisionTreeRegressor

In [136]:
df = pd.read_csv("Top.csv")

In [137]:
df

Unnamed: 0      Zone           State         City  \
0             0  Northern           Delhi        Delhi   
1             1  Northern           Delhi        Delhi   
2             2  Northern           Delhi        Delhi   
3             3  Northern           Delhi        Delhi   
4             4  Northern           Delhi        Delhi   
..          ...       ...             ...          ...   
320         320   Western         Gujarat  Gandhinagar   
321         321   Central   Uttar Pradesh         Agra   
322         322   Central  Madhya Pradesh       Bhopal   
323         323  Northern       Rajasthan       Jaipur   
324         324  Northern       Rajasthan       Jaipur   

                             Name          Type Establishment Year  \
0                      India Gate  War Memorial               1921   
1                  Humayun's Tomb          Tomb               1572   
2               Akshardham Temple        Temple               2005   
3            Waste to Wonder Park    Theme Park               2019   
4                   Jantar Mantar   Observatory               1724   
..                            ...           ...                ...   
320                    Akshardham        Temple               1992   
321                     Agra Fort          Fort               1565   
322  Madhya Pradesh Tribal Museum        Museum               2013   
323                   City Palace        Palace               1727   
324            Albert Hall Museum        Museum               1887   

     time needed to visit in hrs  Google review rating  Entrance Fee in INR  \
0                            0.5                   4.6                    0   
1                            2.0                   4.5                   30   
2                            5.0                   4.6                   60   
3                            2.0                   4.1                   50   
4                            2.0                   4.2                   15   
..                           ...                   ...                  ...   
320                          3.0                   4.6                    0   
321                          2.0                   4.5                   40   
322                          2.0                   4.7                   10   
323                          2.0                   4.4                  200   
324                          2.0                   4.5                  200   

    Airport with 50km Radius Weekly Off   Significance DSLR Allowed  \
0                        Yes       None     Historical          Yes   
1                        Yes       None     Historical          Yes   
2                        Yes       None      Religious           No   
3                        Yes     Monday  Environmental          Yes   
4                        Yes       None     Scientific          Yes   
..                       ...        ...            ...          ...   
320                      Yes     Monday      Religious           No   
321                      Yes       None     Historical          Yes   
322                      Yes     Monday       Cultural          Yes   
323                      Yes       None     Historical          Yes   
324                      Yes       None     Historical          Yes   

     Number of google review in lakhs Best Time to visit  
0                                2.60            Evening  
1                                0.40          Afternoon  
2                                0.40          Afternoon  
3                                0.27            Evening  
4                                0.31            Morning  
..                                ...                ...  
320                              0.18                All  
321                              1.30          Afternoon  
322                              0.15                All  
323                              0.51            Morning  
324             

In [138]:
col = ['Type','Google review rating','Number of google review in lakhs','Entrance Fee in INR']
df = df[col]
df

Type  Google review rating  Number of google review in lakhs  \
0    War Memorial                   4.6                              2.60   
1            Tomb                   4.5                              0.40   
2          Temple                   4.6                              0.40   
3      Theme Park                   4.1                              0.27   
4     Observatory                   4.2                              0.31   
..            ...                   ...                               ...   
320        Temple                   4.6                              0.18   
321          Fort                   4.5                              1.30   
322        Museum                   4.7                              0.15   
323        Palace                   4.4                              0.51   
324        Museum                   4.5                              0.63   

     Entrance Fee in INR  
0                      0  
1                     30  
2                     60  
3                     50  
4                     15  
..                   ...  
320                    0  
321                   40  
322                   10  
323                  200  
324                  200  

[325 rows x 4 columns]

In [139]:
df['Entrance Fee in INR'].unique()

array([   0,   30,   60,   50,   15,   35,   20,   80,   70,  500, 1149,
        550,   25, 1150, 2500,   10, 3500,  200, 7500,  350,  300,  100,
         40,  750,   75,  150, 1500,    5,  250,   65,  650, 1100,  890],
      dtype=int64)

In [140]:
df['Entrance Fee in INR'].value_counts()

0       183
50       21
20       19
30       13
10       12
100       8
500       7
40        7
25        6
300       5
15        5
150       4
35        4
200       4
60        4
1149      2
2500      2
80        2
250       2
1500      2
1100      1
650       1
65        1
5         1
3500      1
75        1
750       1
350       1
7500      1
1150      1
550       1
70        1
890       1
Name: Entrance Fee in INR, dtype: int64

In [141]:
df = df[df['Entrance Fee in INR'] != 0]

In [142]:
df['Entrance Fee in INR'].value_counts()

50      21
20      19
30      13
10      12
100      8
40       7
500      7
25       6
15       5
300      5
150      4
60       4
200      4
35       4
2500     2
250      2
1149     2
80       2
1500     2
1100     1
650      1
65       1
5        1
750      1
75       1
1150     1
70       1
350      1
7500     1
550      1
3500     1
890      1
Name: Entrance Fee in INR, dtype: int64

In [143]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 142 entries, 1 to 324
Data columns (total 4 columns):
 #   Column                            Non-Null Count  Dtype  
---  ------                            --------------  -----  
 0   Type                              142 non-null    object 
 1   Google review rating              142 non-null    float64
 2   Number of google review in lakhs  142 non-null    float64
 3   Entrance Fee in INR               142 non-null    int64  
dtypes: float64(2), int64(1), object(1)
memory usage: 5.5+ KB


In [144]:
df['Google review rating'] = df['Google review rating'].astype('int64')
df['Number of google review in lakhs'] = df['Number of google review in lakhs'].astype('int64')

In [145]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 142 entries, 1 to 324
Data columns (total 4 columns):
 #   Column                            Non-Null Count  Dtype 
---  ------                            --------------  ----- 
 0   Type                              142 non-null    object
 1   Google review rating              142 non-null    int64 
 2   Number of google review in lakhs  142 non-null    int64 
 3   Entrance Fee in INR               142 non-null    int64 
dtypes: int64(3), object(1)
memory usage: 5.5+ KB


In [146]:
df.describe()

Google review rating  Number of google review in lakhs  \
count            142.000000                        142.000000   
mean               3.943662                          0.169014   
std                0.309991                          0.704311   
min                1.000000                          0.000000   
25%                4.000000                          0.000000   
50%                4.000000                          0.000000   
75%                4.000000                          0.000000   
max                4.000000                          7.000000   

       Entrance Fee in INR  
count           142.000000  
mean            265.056338  
std             779.569628  
min               5.000000  
25%              20.000000  
50%              50.000000  
75%             150.000000  
max            7500.000000

In [147]:
df.shape

(142, 4)

In [148]:
df = pd.get_dummies(df,dtype='int')

In [149]:
df

Google review rating  Number of google review in lakhs  \
1                       4                                 0   
2                       4                                 0   
3                       4                                 0   
4                       4                                 0   
7                       4                                 1   
..                    ...                               ...   
318                     4                                 0   
321                     4                                 1   
322                     4                                 0   
323                     4                                 0   
324                     4                                 0   

     Entrance Fee in INR  Type_Adventure Sport  Type_Amusement Park  \
1                     30                     0                    0   
2                     60                     0                    0   
3                     50                     0                    0   
4                     15                     0                    0   
7                     35                     0                    0   
..                   ...                   ...                  ...   
318                   50                     0                    0   
321                   40                     0                    0   
322                   10                     0                    0   
323                  200                     0                    0   
324                  200                     0                    0   

     Type_Aquarium  Type_Beach  Type_Bird Sanctuary  Type_Botanical Garden  \
1                0           0                    0                      0   
2                0           0                    0                      0   
3                0           0                    0                      0   
4                0           0                    0                      0   
7                0           0                    0                      0   
..             ...         ...                  ...                    ...   
318              0           0                    0                      0   
321              0           0                    0                      0   
322              0           0                    0                      0   
323              0           0                    0                      0   
324              0           0                    0                      0   

     Type_Cave  ...  Type_Temple  Type_Temples  Type_Theme Park  Type_Tomb  \
1            0  ...            0             0                0          1   
2            0  ...            1             0                0          0   
3            0  ...            0             0                1          0   
4            0  ...            0             0                0          0   
7            0  ...            0             0                0          0   
..         ...  ...          ...           ...              ...        ...   
318          0  ...            0             0                0          0   
321          0  ...            0             0                0          0   
322          0  ...            0             0                0          0   
323          0  ...            0             0                0          0   
324          0  ...            0             0                0          0   

     Type_Tombs  Type_Valley  Type_Vineyard  Type_Waterfall  \
1             0            0              0               0   
2             0            0              0               0   
3             0            0              0               0   
4             0            0              0               0   
7             0            0              0               0   
..          ...          ...            ...             ...   
318           0            0              0               0   
321           0  

In [150]:
X = df.drop(columns = ['Entrance Fee in INR'])
Y = df['Entrance Fee in INR']

In [151]:
X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size=0.3)

In [152]:
X_train.shape

(99, 46)

In [153]:
model_lin = LinearRegression()
model_lin.fit(X_train,Y_train)

LinearRegression()

In [154]:
model_lin.predict(X_test)

array([-1.50000000e+00,  2.48625000e+02,  1.05205425e+16,  1.56625000e+02,
        1.56625000e+02,  2.48625000e+02,  5.43750000e+01,  5.17500000e+01,
        6.86147892e+14,  3.07500000e+02,  1.08875000e+02,  1.56625000e+02,
        4.26250000e+01,  2.32750000e+02,  8.75000000e+00,  1.19262500e+03,
        5.17500000e+01,  5.17500000e+01,  1.20625000e+02,  7.50587500e+03,
        7.88665082e+15,  1.12401556e+15,  1.56625000e+02,  4.26250000e+01,
        5.17500000e+01,  2.21250000e+01,  1.20873918e+15,  1.98102217e+16,
        1.56625000e+02,  1.56625000e+02,  1.56625000e+02,  1.20625000e+02,
        4.26250000e+01,  3.07500000e+02,  1.02487500e+03,  1.08875000e+02,
        1.20625000e+02,  1.08875000e+02,  1.12401556e+15,  1.12401556e+15,
        1.02500000e+02,  1.20873918e+15,  1.79750000e+02])

In [155]:
model_lin.score(X_train,Y_train)

0.9810091646417493

In [156]:
model_lin.score(X_test,Y_test)

-3.0425303404818043e+25

In [157]:
model_las = Lasso(alpha = 0.001,max_iter = 1,tol=0.00001)
model_las.fit(X_train,Y_train)

Lasso(alpha=0.001, max_iter=1, tol=1e-05)

In [158]:
model_las.predict(X_test)

array([-164.85325544,  260.41465851,  162.66717239,  171.15596895,
        171.15596895,  260.41465851,  124.44604664,   23.41876152,
        162.66717239,  254.69954473,   72.018824  ,  171.15596895,
         38.77475   ,  360.97757792,   30.27666869, 1843.77454991,
         23.41876152,   23.41876152,  129.1554653 , 7530.69978134,
        451.96647447,  162.66717239,  171.15596895,   38.77475   ,
         23.41876152,   26.51476513,  162.66717239,  162.66717239,
        171.15596895,  171.15596895,  171.15596895,  129.1554653 ,
         38.77475   ,  254.69954473,  975.87664366,   72.018824  ,
        129.1554653 ,   72.018824  ,  162.66717239,  162.66717239,
         99.37952062,  363.79301121,  182.92094142])

In [159]:
model_las.score(X_train,Y_train)

0.9773104858963945

In [160]:
model_las.score(X_test,Y_test)

-2.9470652374922257

In [161]:
model_rid = Ridge(alpha = 0.0000001,max_iter = 1,tol=1000)
model_rid.fit(X_train,Y_train)

Ridge(alpha=1e-07, max_iter=1, tol=1000)

In [162]:
model_rid.score(X_train,Y_train)

0.9810344227684691

In [163]:
model_rid.score(X_test,Y_test)

-2.850945974868287

In [164]:
model_tree = DecisionTreeRegressor()
model_tree.fit(X_train,Y_train)

DecisionTreeRegressor()

In [165]:
model_tree.predict(X_test)

array([  10.        ,  247.5       ,   38.75      ,  160.        ,
        160.        ,  247.5       ,   50.        ,   45.        ,
         38.75      ,  300.        ,  125.        ,  160.        ,
         38.75      ,  247.5       ,   10.        , 1019.5       ,
         45.        ,   45.        ,  118.57142857, 7500.        ,
         50.        ,   38.75      ,  160.        ,   38.75      ,
         45.        ,   17.5       ,   38.75      ,   38.75      ,
        160.        ,  160.        ,  160.        ,  118.57142857,
         38.75      ,  300.        , 1019.5       ,  125.        ,
        118.57142857,  125.        ,   38.75      ,   38.75      ,
        100.        ,   25.        ,  181.66666667])

In [166]:
model_tree.score(X_train,Y_train)

0.981129954458411

In [167]:
model_tree.score(X_test,Y_test)

-2.9194545852613447